locale : "fr"
title  : "Netlify CMS test"
url    : https://upbeat-euler-2e4306.netlify.com
baseurl  :

encoding: "utf-8"
timezone: "Europe/Paris"

defaults:
  - scope:
      type: posts
    values:
      layout: post
